### ISSUE TITLE
Editor will not allow mixed case file names

### ISSUE THREAD

**Issue by DaveAtKitronik** [microbit-foundation/python-editor-v3#1026]
The new editor wil not allow creation of mixed case file names: 
![image](https://user-images.githubusercontent.com/25896029/195027763-16ecafe3-1095-4f7f-9b94-29b6c5f54d2a.png)

However the editor is parsing the imports with case sensitivity, and files created elsewhere and opened into the project can be mixed case:
![image](https://user-images.githubusercontent.com/25896029/195028647-88bb1f84-7b77-420a-b961-ae498ba3c229.png)

The file naming restriction seems arbitrary, and when people are copying code from examples which are mixed case this will cause confusion. 
Suggest the refusal to allow mixed cases is dropped.

**Comment by microbit-matt-hillsdon** [comment]
Hi @DaveAtKitronik, thanks for the feedback.

The intention of the check in the create file dialog was to guide students towards conventional Python naming [as documented in PEP8](https://peps.python.org/pep-0008/#package-and-module-names) when creating modules. I think some guidance here is helpful but it's interesting to learn that it causes an issue here. I'll have a chat with the team.

If you already have this module as a file with the KitronikMoveMotor.py name and open it in the editor then it should work well. It's just the create dialog that has this restriction. For example, if I drag the copy at https://github.com/KitronikLtd/micropython-microbit-kitronik-MOVE-motor/blob/master/KitronikMOVEMotor.py in then all works well. That version has the micro:bit module comments at the top, so the editor knows to open it as an additional module not the main file. This works via drag and drop or the open dialog. Those options can also open a main.py file at the same time my dragging or selecting multiple both so could be a good option for your users.

If the module doesn't have the special comment at the top then [the process to open it is documented here](https://support.microbit.org/support/solutions/articles/19000135210-python-editor-guide#:~:text=from%20the%20menu.-,Using%20the%20projects%20menu,-The%20projects%20section).

**Comment by DaveAtKitronik** [comment]
Whilst recommending / guiding towards lowercase filenames is fine, banning the creation of camelCase.py or PascalCase.py seems incorrect and overly strict. There is cognitive dissonance with modules (which could be camelCased), and the interpreter is case sensitive.

How do you 'drag and drop' a module? I cannot get that to work - is it documented somewhere?

**Comment by microbit-matt-hillsdon** [comment]
I've revised our support documentation around adding modules to the editor for the V3 editor: https://support.microbit.org/support/solutions/articles/19000106811-adding-a-module-to-the-python-editor

If your modules have the magic header (as the one on your GitHub does) then you can drag and drop them into the editor from e.g. the Downloads folder or use the Open button and you should get a good experience where they're identified as modules and added alongside the main code. You can drag and drop or Open more than one file at once, so your users could open an example main.py alongside the KitronikMOVEMotor module in one step. Another option is an example hex file that already contains a main.py and the module.

On the "Create file" issue, we've discussed this and plan to relax the validation so that users who need to create modules with non-lowercase names can still click "Create". We'll still show the message to guide newer users towards PEP8 style names.

**Comment by microbit-matt-hillsdon** [comment]
Now live on https://python.microbit.org in [v3.0.5](https://github.com/microbit-foundation/python-editor-v3/releases/tag/v3.0.5). Closing.
