### ISSUE TITLE
Drag and drop indentation

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-v3#539]
Without a new line with no indentation at the bottom of the file, drag and drop won't allow you to drop code beyond the last line without any indentation - it is always at the indentation level of the last line. See video below:

https://user-images.githubusercontent.com/95928279/152361196-ce4b02db-8977-4f94-b24f-5bcea0dad45e.mp4

**Comment by microbit-matt-hillsdon** [comment]
On https://github.com/microbit-foundation/python-editor-v3/pull/1037 you can choose an arbitrary indent in this scenario, with the exception that, because of the while True, we prevent you dropping code after it to avoid the confusion that would result. If you change the while to an if you can pick the 0th indent.
