### ISSUE TITLE
Unused function error only triggered if function doesn't start with `_`

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/python-editor-v3#809]
## Bug Description

I'm not sure if the "unused function" error is silenced, but there is a different in behaviour between `def foo(): ...` and `def _foo():...`

## How To Reproduce

This screenshot shows the issue, the "this function is unused" appears with `_foo` only. And it also breaks the structure highlighting:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/29712657/178156921-91b5f127-3864-43f1-97f8-de3e4b6d43c1.png">

```python
def foo():
    if True:
        while True:
            pass

def _foo():
    a = 10
    b = 100
    c = 1000
    if True:
        while True:
            pass
```

## Expected behavior

Both functions to error, or neither.
Code structure highlighting to continue working.

## Screenshots

In "How to reproduce" secton

## Environment

N/A

## Additional context

N/A

**Comment by microbit-matt-hillsdon** [comment]
I think this intentional behaviour by Pyright, because _foo is not considered part of the public interface of the module and not used within it. We could attempt to change this but I'm not sure I see the value. I suspect folks using underscores in this way may be doing so for this distinction.

The effect on code structure highlighting seems like it might be an independent bug affecting function bodies that start with an assignment. I've split that into https://github.com/microbit-foundation/python-editor-v3/issues/1022 and hope to look at it soon.

**Comment by microbit-matt-hillsdon** [comment]
Closing this as the _foo vs foo behaviour is as per Pyright's design which doesn't worth trying to deviate from here. The highlighting issues are on #1022 now.
